const API='https://ai-trader-backend-mgwt.onrender.com';
const $=id=>document.getElementById(id);const fmt=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let chart=null;
function beep(freq=660){try{const a=new (window.AudioContext||window.webkitAudioContext)();const o=a.createOscillator();const g=a.createGain();o.frequency.value=freq;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.12);setTimeout(()=>a.close(),160)}catch(e){}}
async function api(path,opts={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opts});const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={raw:t}} if(!r.ok)throw new Error(j.detail||j.raw||'Erro API');return j}
function showApp(){ $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');refresh();}
function statusPill(el,on,textOn,textOff){el.classList.toggle('off',!on);el.textContent=on?textOn:textOff}
$('loginBtn').onclick=async()=>{beep();$('loginMsg').textContent='Conectando na IQ Option...';try{const res=await api('/api/iq/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value,account_type:$('account').value})});$('loginMsg').textContent=`Conectado. Saldo: ${fmt(res.balance)}`;setTimeout(showApp,700)}catch(e){$('loginMsg').textContent='Falha: '+e.message}};
$('logoutBtn').onclick=async()=>{beep(300);try{await api('/api/iq/logout',{method:'POST'})}catch(e){}location.reload()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{beep(520);document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active');$('pageTitle').textContent=b.textContent});
$('themeBtn').onclick=()=>{beep(760);document.body.classList.toggle('light')};
$('startBtn').onclick=async()=>{beep();try{await api('/api/robot/start',{method:'POST'});refresh()}catch(e){alert(e.message)}};$('pauseBtn').onclick=async()=>{beep(440);await api('/api/robot/pause',{method:'POST'});refresh()};$('stopBtn').onclick=async()=>{beep(260);await api('/api/robot/stop',{method:'POST'});refresh()};
$('saveCfg').onclick=async()=>{beep();await api('/api/config',{method:'POST',body:JSON.stringify({daily_goal:+cfgGoal.value,entry_value:+cfgEntry.value,stop_loss:+cfgLoss.value,stop_gain:+cfgGain.value,max_operations:200,max_losses:4,start_time:'00:00',end_time:'23:59',min_confidence:+cfgConf.value,mode:'Contínuo DEMO',expiration_minutes:1,trade_interval_seconds:10,execute_real_demo_orders:true,market_type:cfgMarket.value})});alert('Configurações salvas')};
function drawCandles(cs){const labels=cs.map(c=>c.time), data=cs.map(c=>c.close);if(chart)chart.destroy();chart=new Chart($('marketChart'),{type:'line',data:{labels,datasets:[{label:'Preço',data,borderColor:'#20d66b',backgroundColor:'rgba(32,214,107,.1)',fill:true,tension:.25}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#8da0b8'}}},scales:{x:{ticks:{color:'#8da0b8',maxTicksLimit:8},grid:{color:'#1d314f'}},y:{ticks:{color:'#8da0b8'},grid:{color:'#1d314f'}}}}})}
async function refresh(){try{const d=await api('/api/dashboard');const c=d.cards;statusPill($('apiStatus'),true,'API online','API offline');statusPill($('iqStatus'),c.iq_connected,'IQ conectada','IQ offline');statusPill($('robotStatus'),c.robot==='running','Robô executando',c.robot==='paused'?'Robô pausado':'Robô parado');$('sideStatus').textContent=c.iq_connected?'Conectado':'Offline';$('balance').textContent=fmt(c.current_balance);$('profit').textContent=fmt(c.daily_profit);$('profit').className=c.daily_profit>=0?'green':'red';$('goal').textContent=fmt(c.daily_goal);$('goalBar').style.width=(c.goal_pct||0)+'%';$('sync').textContent=c.last_sync?'Última sync '+c.last_sync:'Sem sincronização';$('robotBig').textContent=c.robot==='running'?'Executando':c.robot==='paused'?'Pausado':'Parado';$('pulse').classList.toggle('hidden',c.robot!=='running');const best=d.best_signal||d.opportunities[0];$('aiBox').innerHTML=`<b>Ativo:</b> ${best.asset}<br><b>Sinal:</b> <span class='tag ${best.action}'>${best.action}</span><br><b>Confiança:</b> ${best.probability}%<br><b>Próximo horário provável:</b> ${best.best_time}<br><b>Mercado:</b> ${best.market_label||c.market_type||'AUTO'}<br><b>Dados:</b> ${best.candles_real?'Candles reais IQ Option':'Candles visuais/simulados'}<br><small>${d.message||''}</small>`;$('opps').innerHTML=d.opportunities.map(o=>`<div class='opp'><div><b>${o.asset}</b><p>${o.trend} · ${o.market_label||''} · RSI ${o.rsi} · ${o.level} · ${o.candles_real?'Real':'Visual'}</p></div><div><b class='${o.probability>=75?'green':'red'}'>${o.probability}%</b> <span class='tag ${o.action}'>${o.action}</span><p>${o.best_time}</p></div></div>`).join('');$('trades').innerHTML=(d.trades||[]).map(t=>`<tr><td>${t.time}</td><td>${t.asset}</td><td>${t.market||'-'}</td><td>${t.direction}</td><td class='${t.result==='WIN'?'green':'red'}'>${t.result}</td><td>${fmt(t.profit)}</td><td>${t.confidence}%</td></tr>`).join('')||'<tr><td colspan="7">Nenhuma operação registrada ainda.</td></tr>';$('logs').innerHTML=(d.logs||[]).map(l=>`<div class='log'><b>${l.time}</b> — ${l.message}</div>`).join('')||'<div class="log">Aguardando atividade.</div>';const candles=await api('/api/candles/'+best.asset.replace('/','-'));drawCandles(candles.candles)}catch(e){statusPill($('apiStatus'),false,'API online','API offline');$('loginMsg').textContent='Falha ao carregar API: '+e.message}}
setInterval(()=>{if(!$('appView').classList.contains('hidden'))refresh()},5000);
